repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9012
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      -   id: roxygenize
          # roxygen requires loading pkg -> add dependencies from DESCRIPTION
          additional_dependencies:
          -    dplyr
          -    ggplot2
          -    magrittr
          -    readr
          -    stats
          -    tibble
          -    tidyr
          -    here
          -    futile.logger
          -    janitor
          -    jsonlite
          -    progress
          -    purrr
          -    stringr
          -    utils
      - id: use-tidy-description
  - repo: local
    hooks:
      - id: test-unit
        name: Run unit tests
        entry: Rscript -e "testthat::test_dir('tests')"
        language: system
        files: \.(R|r)$
        pass_filenames: false
