## Copyright 2022 Matthew A. Clarke, Fisher Lab, UCL <matthew.clarke@ucl.ac.uk>

#' Check that all perturbations are within the range of the node
#' affected. Otherwise BMA will run without perturbation silently.
#' @title check_perts_in_range
#' @param spec_levels specification dataframe generated by
#'     \code{\link{convert_spec_levels}}
#' @return Stop if perturbations are outside range of nodes
#' @export
check_perts_in_range <- function(spec_levels) {
    x <- spec_levels %>%
        dplyr::select(source,
               experiment_particular,
               gene,
               perturbation_bma,
               expectation_bma,
               range_from,
               range_to)
    perturbation_out_range <- dplyr::filter(x,
                                     perturbation_bma < range_from |
                                     perturbation_bma > range_to)
    expectation_out_range <- dplyr::filter(x,
                                    expectation_bma < range_from |
                                    expectation_bma > range_to)

    if (nrow(perturbation_out_range) > 0) {
        futile.logger::flog.error(
            stop(
                "There are perturbations that are outside the range the node can take: \n",

                paste(utils::capture.output(dplyr::select(perturbation_out_range, -expectation_bma)), collapse = "\n"),
                call. = FALSE
            ),
            name = log_file
        )
    }

    if (nrow(expectation_out_range) > 0) {
        futile.logger::flog.error(
            stop(
                "There are perturbations that are outside the range the node can take: \n",
                paste(utils::capture.output(dplyr::select(expectation_out_range, -perturbation_bma)), collapse = "\n"),
                call. = FALSE
            ),
            name = log_file
        )
    }
}
