## Copyright 2021 Matthew A. Clarke, Fisher Lab <matthewaclarke1991@gmail.com>

#' Take a df of nodes from json file, annotated with level of activity
#' and annotate all with filename prefix and BioCheckConsole command
#' argument needed to change it's value
#'
#' @param df dataframe of nodes and ids generated by
#'     \code{\link{get_netw_variables}}
#' @param id_col name of column in `df` containing BMA node ids, as a
#'     string, default "id"
#' @param activity_col name of column in `df` containing activity
#'     level to change node to in perturbations, as a string, default
#'     "activity"
#' @param node_col name of column in `df` containing the name of the
#'     node/gene from BMA network, as a string, default "name"
#' @return dataframe with a column of arguments to pass to a call of
#'     BioCheckConsole, `command_arg` and a column of the filename
#'     prefixes for the output of this command, `filename_part`
#' @family combination_therapy
#' @seealso \code{\link{get_netw_variables}}
#' @export

make_command_args <- function(df,
                              id_col = "id",
                              activity_col = "activity",
                              node_col = "name") {
    # Check if id column contains non-numeric values or NA
    id_values <- df[[id_col]]
    if (!is.numeric(id_values)) {
        stop(paste("Column", id_col, "must be numeric. Found values:",
                   paste(head(unique(id_values), 5), collapse = ", ")))
    }
    if (any(is.na(id_values))) {
        na_positions <- which(is.na(id_values))
        stop(paste("Column", id_col, "contains NA values at positions:",
                   paste(head(na_positions, 5), collapse = ", ")))
    }

    # Check if activity column contains non-numeric values or NA
    activity_values <- df[[activity_col]]
    if (!is.numeric(activity_values)) {
        stop(paste("Column", activity_col, "must be numeric. Found values:",
                   paste(head(unique(activity_values), 5), collapse = ", ")))
    }
    if (any(is.na(activity_values))) {
        na_positions <- which(is.na(activity_values))
        stop(paste("Column", activity_col, "contains NA values at positions:",
                   paste(head(na_positions, 5), collapse = ", ")))
    }

    out <- dplyr::mutate(df,
                         command_arg = paste("-ko",
                                             !!rlang::sym(id_col),
                                             !!rlang::sym(activity_col)),
                         filename_part = paste(!!rlang::sym(node_col),
                                               !!rlang::sym(activity_col),
                                               sep = "__"))
    return(out)
}

#' Convert a list of background mutations for combination screen
#'
#' Convert a 3 x n dataframe of backgrounds in long format, where one
#' column is the name of the background called "background", one is a
#' list of nodes called "name" and one is the activity the nodes
#' should be fixed to in this background called "activity"
#'
#' @param backgrounds data frame as above
#' @param netw_variables data from of network variables generated by
#'     \code{\link{get_netw_variables}}
#' @param node_col name of the column with the node
#'     names. \code{\link{get_netw_variables}} defaults to `name`.
#' @return data frame with annotation of all the arguments to pass to
#'     BioCheckConsole for each background, and a filename part that
#'     describes these. Unlike \code{\link{make_command_args}} these
#'     are grouped so that each background is a single row, even if
#'     this is multiple perturbations of the network.
#' @family combination_therapy
#' @export
make_bkg_commands_combo <- function(backgrounds,
                                    netw_variables,
                                    node_col = "name") {

    if (!((node_col %in% colnames(backgrounds)) &
         (node_col %in% colnames(netw_variables)))) {
        stop("Error: It looks like the name of the column with node names, set as `node_col`, is not present in 'backgrounds' or 'netw_variables'. If you have renamed it make sure it is consistent between the two arguments and that you supply it with the `node_col` argument")
    }

    ## make a dataframe with the command argument and corresponding
    ## part of a filename for a node per row by joining backgrounds
    ## and netw variables by gene/nodename
    background_args <- dplyr::left_join(backgrounds, netw_variables,
                                 by = node_col) %>%
        dplyr::select(background, rlang::sym(node_col), id, activity) %>%
        make_command_args(node_col = node_col)

    ## group rows of the same background together and combine commands
    ## and filename prefixes
    background_commands <- background_args %>%
        dplyr::group_by(background) %>%
        dplyr::summarise(filename_prefix =
                             paste(filename_part, collapse = "__"),
                  command_arg = paste(command_arg, collapse = " "))

    return(background_commands)
}

#' Generate a dataframe with columns describing for BMA all possible
#' single activations and inhibitions of nodes in a network
#'
#' @param netw_variables data frame of node names, ids, range_from and
#'     range_to for a network, generated by
#'     \code{\link{get_netw_variables}}
#' @param node_col name of the column with the node
#'     names. \code{\link{get_netw_variables}} defaults to `name`.
#' @return data frame annotated by command arguments and filenames for
#'     perturbations of all nodes
#' @family combination_therapy
#'@seealso \code{\link{make_command_args}},
#'     \code{\link{get_netw_variables}}
#' @export
make_single_muts <- function(netw_variables, node_col = "name") {
    if (!(node_col %in% colnames(netw_variables))) {
        stop("Error: It looks like the name of the column with node names, set as `node_col`, is not present in'netw_variables'.")
    }

    s_muts <- netw_variables %>%
        dplyr::select(dplyr::all_of(node_col), id, range_from, range_to) %>%
        dplyr::rename("inhibition" = range_from,
                      "activation" = range_to) %>%
        tidyr::pivot_longer(cols = c("activation", "inhibition"),
                            names_to = "type",
                            values_to = "activity") %>%
        make_command_args(node_col = node_col)

    ## Add a baseline case for each background
    baseline <- tibble::tibble(!!(node_col) := "baseline",
                       id = NA,
                       type = NA,
                       activity = NA,
                       command_arg = "",
                       filename_part = "baseline")
    s_muts <- dplyr::bind_rows(s_muts, baseline)
    return(s_muts)
}

#' Generate a dataframe with columns describing for BMA all possible
#' pairs of activations and inhibitions of nodes in a network
#'
#' @param netw_variables data frame of node names, ids, range_from and
#'     range_to for a network, generated by
#'     \code{\link{get_netw_variables}}
#' @param node_col name of the column with the node
#'     names. \code{\link{get_netw_variables}} defaults to `name`.
#' @return data frame annotated by command arguments and filenames for
#'     perturbations of all nodes
#' @seealso \code{\link{make_command_args}},
#'     \code{\link{get_netw_variables}}
#' @family combination_therapy
#' @export
make_pair_muts <- function(netw_variables, node_col = "name") {
    genes <- dplyr::pull(netw_variables, dplyr::all_of(node_col))
    if (length(genes) < 2) {
        stop("Need at least 2 nodes to create pairs")
    }
    netw_variables_short <- dplyr::select(netw_variables,
                                          dplyr::all_of(node_col),
                                          id,
                                          range_from,
                                          range_to) %>%
        dplyr::rename("inhibition" = range_from,
                      "activation" = range_to)

    # Create pairs with explicit column names to avoid tibble warnings
    pairs_matrix <- combn(genes, 2) %>% t()
    colnames(pairs_matrix) <- c("a", "b")

    pairs <- tibble::as_tibble(pairs_matrix) %>%
        dplyr::left_join(netw_variables_short, by = c("a" = {{node_col}})) %>%
        dplyr::rename("id_a" = "id") %>%
        tidyr::pivot_longer(cols = c("inhibition", "activation"),
                            names_to = "type_a",
                            values_to = "activity_a") %>%
        dplyr::left_join(netw_variables_short, by = c("b" = {{node_col}})) %>%
        dplyr::rename("id_b" = "id") %>%
        tidyr::pivot_longer(cols = c("inhibition", "activation"),
                            names_to = "type_b",
                            values_to = "activity_b") %>%
        dplyr::mutate(command_arg = paste("-ko", id_a, activity_a,
                                          "-ko", id_b, activity_b),
                      filename_part = paste(a, activity_a, b, activity_b, sep = "__"))
    return(pairs)
}

##' Import drugs and sanitise drug names so they cannot cause problems
##' when converted to file names
##'
##' @title import_drugs_clean
##' @param drug_path path to drugs CSV
##' @param show_col_types Mutes printing of columns types using readr::read_csv
##' @return tibble of drugs with drug names sanitised
##' @export
import_drugs_clean <- function(drug_path, show_col_types = FALSE) {
    drugs <- readr::read_csv(drug_path,
                             show_col_types = show_col_types, lazy = FALSE) %>%
        dplyr::mutate(drug = purrr::map_chr(drug, janitor::make_clean_names))
    return(drugs)
}




#' Check whether drugs applied to the network have corresponding nodes
#' in the network
#'
#' @param drugs data frame of drugs to apply with columns: 'drug' with
#'     the name of the drug; 'node' with the node(s) affect (for
#'     multiple nodes specify one node per row with the same drug
#'     name) and 'activity' the numerical level to which the drug
#'     should set the affected node
#' @param netw_variables data frame of node names, ids, range_from and
#'     range_to for a network, generated by
#'     \code{\link{get_netw_variables}}
#' @param node_col_name name of the columns specifying nodes
#' @return Stop if nodes are missing from network, and report missing nodes
#' @family combination_therapy
#' @export
check_drug_nodes <- function(drugs,
                             netw_variables,
                             node_col_name) {
    ## Check if all nodes drugged are in network
    if (!all(unique(dplyr::pull(drugs, dplyr::all_of(node_col_name))) %in%
             unique(dplyr::pull(netw_variables, dplyr::all_of(node_col_name))))) {
        stop(paste(
            "Nodes in drug list not in network: ",
            capture.output(
                setdiff(unique(dplyr::pull(drugs, dplyr::all_of(node_col_name))),
                        unique(dplyr::pull(netw_variables, dplyr::all_of(node_col_name)))))))
    }
}

#' Check whether drugs applied to the network have conflicting effects
#' on the same node, which will cause issues in combinations
#'
#' @param drugs data frame of drugs to apply with columns: 'drug' with
#'     the name of the drug; 'node' with the node(s) affect (for
#'     multiple nodes specify one node per row with the same drug
#'     name) and 'activity' the numerical level to which the drug
#'     should set the affected node
#' @param node_col_name name of the columns specifying nodes
#' @return Stop if there are conflicts
#' @family combination_therapy
#' @importFrom rlang .data
#' @export
check_drug_conflicts <- function(drugs, node_col_name) {
    d_conflicts <- drugs %>%
        dplyr::select(dplyr::all_of(node_col_name), activity) %>%
        dplyr::distinct() %>%
        dplyr::group_by(.data[[node_col_name]]) %>%
        dplyr::summarise(n_unique = dplyr::n()) %>%
        dplyr::filter(n_unique > 1)
    if (nrow(d_conflicts) > 0) {
        stop("Drug combinations have conflicting effects on the same node")
    } else {
        "Drug conflicts check: passed"
    }
}


#' Get the BioCheckConsole command line commands to effect the drug
#' perturbations, and assign filename parts to record perturbations
#' applied
#'
#' @param drugs data frame of drugs to apply with columns: 'drug' with
#'     the name of the drug; 'node' with the node(s) affect (for
#'     multiple nodes specify one node per row with the same drug
#'     name) and 'activity' the numerical level to which the drug
#'     should set the affected node. Drug names will be sanitised with
#'     janitor::make_clean_names as they must be passed to the command
#'     line
#' @param netw_variables data frame of node names, ids, range_from and
#'     range_to for a network, generated by
#'     \code{\link{get_netw_variables}}
#' @param node_col_name name of the columns specifying nodes
#' @return Data frame of: 'drug' sanitised drug name;
#'     'drug_name_original' original name, 'node' node affected,
#'     'activity' activity of the node under the effects of the drug,
#'     'id' BMA node id, 'range_from' lower bound of range of node in
#'     network, 'range_to' upper bound of range of node in network,
#'     'formula' network target function, 'command arg' command to
#'     cause perturbation in format '-ko id activity',
#'     'alt_filename_part' part of the filename for the results file
#'     corresponding to this perturbation
#' @family combination_therapy
#' @export
get_drugs_commands <- function(drugs, netw_variables, node_col_name) {
    ## Get ids etcs
    drugs_w_nodes <- drugs %>%
        dplyr::select(drug, dplyr::all_of(node_col_name), activity) %>%
        ## Cannot do normal mutate as make_clean_names will make dups
        ## unique, purr avoids this
        dplyr::mutate(drug_name_original = drug) %>%
        dplyr::mutate(drug = purrr::map_chr(drug_name_original, janitor::make_clean_names)) %>%
        dplyr::left_join(netw_variables, by = node_col_name)

    drugs_commands <- make_command_args(drugs_w_nodes, node_col = rlang::sym(node_col_name)) %>%
        dplyr::rename("alt_filename_part" = "filename_part") %>%
        dplyr::mutate(filename_part = paste(drug, NA, sep = "__"))

    return(drugs_commands)
}

#' Check whether drugs applied to the network have effects that are
#' withing the range of the node. If not, BioCheckConsole would fail
#' silently.
#'
#' @param drugs_commands drugs with network variables and command
#'     fragments, generated by \code{\link{get_netw_variables}}
#' @return Stop if there are perturbations out of range and report
#' @family combination_therapy
#' @export
check_drugs_in_range <- function(drugs_commands) {
    activity_out_range <- dplyr::filter(drugs_commands,
                                 activity < range_from |
                                 activity > range_to)
    if (nrow(activity_out_range) > 0) {
        stop(
            "There are perturbations that are outside the range the node can take: \n",
            paste(capture.output(activity_out_range), collapse = "\n"),
            ## see https://stackoverflow.com/a/26083626
            call. = FALSE
        )
    } else {
        message("CHECK PASSED: All drug perturbations are within node ranges")
    }
}

#' Make full commands for single drug perturbations by combining all
#' perturbations for a single drug
#'
#' @param drugs_commands drugs with network variables and command
#'     fragments, generated by \code{\link{get_netw_variables}}
#' @return Dataframe of drug commands for use by
#'     \code{\link{run_all_backgrounds}}
#' @export
make_single_drugs <- function(drugs_commands) {
    drugs_single <- drugs_commands %>%
        dplyr::group_by(drug) %>%
        dplyr::summarise(command_arg = paste(command_arg,
                                             collapse = " "),
                         alt_filename_part = paste(alt_filename_part,
                                                   collapse = "__")) %>%
        dplyr::mutate(filename_part = paste(drug, "NA", sep = "__"))
    return(drugs_single)
}

#' Make full commands for pair drug perturbations by combining all
#' perturbations for a pair drug
#'
#' @param drugs_single drugs with network variables and command
#'     fragments, generated by \code{\link{make_single_drugs}}
#' @return Dataframe of drug commands for use by
#'     \code{\link{run_all_backgrounds}}
#' @export
make_pair_drugs <- function(drugs_single) {
    drugs_pairs <- combn(dplyr::pull(drugs_single, drug), 2) %>%
        t() %>%
        tibble::as_tibble(.name_repair = "minimal") %>%
        setNames(c("a", "b")) %>%
        dplyr::left_join(drugs_single, by = c("a" = "drug")) %>%
        dplyr::left_join(drugs_single, by = c("b" = "drug")) %>%
        dplyr::mutate(filename_part = paste(filename_part.x,
                                            filename_part.y, sep = "__"),
                      alt_filename_part = paste(alt_filename_part.x,
                                                alt_filename_part.y, sep = "__"),
                      command_arg = paste(command_arg.x, command_arg.y)) %>%
        dplyr::select(a, b, filename_part, alt_filename_part, command_arg)
    return(drugs_pairs)
}


#' Given a set of backgrounds and a set of perturbations, annotated
#' with columns of BMA command arguments and corresponding filenames,
#' passes these to BioCheckConsole to generate results with VMCAI
#'
#' @param background_commands data frame of backgrounds generated by
#'     \code{\link{make_bkg_commands_combo}}
#' @param netw_file_path path to network JSON file
#' @param bma_path path to BMA command line installation. The path
#'     is automatically normalized for cross-platform compatibility.
#' @param perts data frame of pertubations e.g. generated by
#'     \code{\link{make_single_muts}} or \code{\link{make_pair_muts}}
#' @param combo_type e.g. "single" or "double":used to label output
#'     directories
#' @param results_dir directory to store results files
#' @param log_file name of log file used to track
#'     results/warnings/errors with futile.logger
#' @param precedence should perturbation or background mutation take
#'     precedence if there are conflicting effects on the same node,
#'     defaults to perturbation
#' @return Results are written as json files by BMA in directories
#'     created with the name of the background and the
#'     combo_type. Individual files are named by combining the file
#'     part of the background and the perturbation as generated by
#'     \code{\link{make_bkg_commands_combo}} and
#'     \code{\link{make_single_muts}} or \code{\link{make_pair_muts}}
#'     respectively.
#' @family combination_therapy
#' @export
run_all_backgrounds <- function(background_commands,
                                netw_file_path,
                                bma_path,
                                perts,
                                combo_type,
                                results_dir,
                                log_file,
                                precedence = "perturbation") {
    ## Normalize BMA path for cross-platform compatibility
    # bma_path <- normalize_bma_path(bma_path)

    ## Log and report in console what type of command is being run as
    ## these can take a long time
    futile.logger::flog.info(
                       print(paste("Running: ", combo_type)),
                       name = log_file)


    ## Loop over all backgrounds
    for (i in seq_len(nrow(background_commands))) {

        ## Separate results for different backgrounds into their own
        ## directories within the specified results directory
        out_dir <- file.path(
            results_dir,
            paste0("RAW__", combo_type,
                   "__",
                   background_commands$background[i]))
        if (!dir.exists(file.path(out_dir))) {
            dir.create(file.path(out_dir))
        }

        ## Combine commands for background and perturbation to pass to
        ## BMA, and full filename recording what the command was.
        commands <- perts %>%
            dplyr::mutate(background = background_commands$background[i],
                          bk_command = background_commands$command_arg[i],
                          bk_filename_part = background_commands$filename_prefix[i],
                          ## full filename separates the background and the
                          ## perturbation using "PERT" so that each can be
                          ## recovered separately from the results filename,
                          ## as BMA cannot send directly to R. Using a
                          ## separator character allows use of
                          ## tidyr::separate for this which is far faster
                          ## than pattern matching and splitting on the
                          ## string for each background filename part.
                          full_filename = paste0(paste(bk_filename_part,
                                                       "PERT",
                                                       filename_part,
                                                       sep = "__"), ".json"),
                          alt_full_filename = paste0(paste(bk_filename_part,
                                                           "PERT",
                                                           alt_filename_part,
                                                           sep = "__"), ".json"))

        ## ORDER MATTERS, if bk_command conflicts with
        ## command_arg, command_arg takes precedence as it
        ## is first
        if (precedence == "perturbation") {
            commands <- dplyr::mutate(commands, full_command =
                                          paste(command_arg, bk_command))
        } else if (precede == "background") {
            commands <- dplyr::mutate(commands, full_command =
                                          paste(bk_command, command_arg))
        } else {
            stop("precedence in case of conflict must be either 'background' or 'perturbation'")
        }

        ## Report stage of loop
        futile.logger::flog.info(
            print(paste("Running:", basename(out_dir),
                    "(", i, "of", nrow(background_commands),
                    "in",
                    combo_type,
                    ")")),
        name = log_file)

        ## Initialise progress bar
        p <- progress::progress_bar$new(total = nrow(commands),
                                        force = TRUE,
                                        clear = FALSE,
                                        format =
                         " [:bar] :percent eta: :eta elapsed: :elapsedfull"
                                        ) # Initialise progress bar

        ## Variable to ensure that if there are existing files and
        ## these are skipped as the results are already generated, the
        ## user is warned but only once per function call
        warned <- FALSE

        ## Run all perturbations
        for (j in seq_len(nrow(commands))) {
            out_file <- file.path(out_dir, commands$full_filename[j])
            alt_out_file <- file.path(out_dir, commands$alt_full_filename[j])
            ## alt filename checks if a drug has already been run as a node
            if (file.exists(out_file)) {
                if (warned == FALSE) {
                    futile.logger::flog.warn(
                                       print(
                                           paste0(
                                               "Skipping existing file: ",
                                               basename(out_file),
                                               "\n This may lead to the very last file being missed, so best to delete that one before running again after an interruption. This warning is shown once per function call. Progress bar will restart below.")),
                                       name = log_file)
                    warned <- TRUE
                    p$tick()
                } else {
                    futile.logger::flog.info(
                                       print(
                                           paste0(
                                               "Skipping existing file: ",
                                               basename(out_file)))
                                     , name = log_file)
                    p$tick()
                }} else if (file.exists(alt_out_file)) {
                     futile.logger::flog.info(
                                        print(
                                            paste("Drug perturbation",
                                                  basename(alt_out_file),
                                                  "already run as node perturbation, duplicating as",
                                                  basename(out_file)))
                                      , name = log_file)
                     file.copy(alt_out_file, out_file)
                     p$tick()
                 } else {
            shell(paste0(bma_path
                       , " -model "
                       , netw_file_path
                       , " -engine VMCAI -nosat -prove "
                       , file.path(out_dir, commands$full_filename[j])
                       , " "
                       , commands$full_command[j])
                  )
            p$tick()
        }
    }
}
}


#' Process the results of combination perturbation screen, assuming
#' two perturbations
#'
#' @param parsed_results raw results read from a directory of json
#'     files using \code{\link{parse_biocheck_dir}}
#' @param phenotypes names of the nodes whose results will be analysed
#'     e.g. "Proliferation"
#' @param log_file log file
#' @param node_col name of the column with the node
#'     names. \code{\link{get_netw_variables}} defaults to `name`.
#' @param pheno_only Boolean. If TRUE, only return measurements for
#'     those nodes listed in \code{phenotypes}.
#' @family combination_therapy
#' @importFrom rlang .data
#' @export
process_results <- function(parsed_results,
                            phenotypes,
                            log_file = log_file,
                            node_col = "name",
                            pheno_only = FALSE) {

    futile.logger::flog.info(print("Processing results"), name = log_file)

    ## Save time/space when processing large files by saving only the
    ## results for key phenotypes
    if (pheno_only == TRUE) {
        results_filter <- parsed_results %>%
            dplyr::filter(.data[[node_col]] %in% phenotypes)
    } else {
        results_filter <- parsed_results
    }

    ## initialise progress bar
    pb_proc <- progress::progress_bar$new(total = nrow(results_filter),
                                          force = TRUE,
                       clear = FALSE,
           format = " [:bar] :percent eta: :eta elapsed: :elapsedfull")
    processed_results <- results_filter %>%
        tidyr::separate(filename, "/", into = c("case", "full_pert")) %>%
        dplyr::mutate(case = stringr::str_remove(case, "RAW__")) %>%
        tidyr::separate(case, "__", into = c("case", "background")) %>%
        tidyr::separate(full_pert, "__PERT__", into = c("bkg_pert", "pert")) %>%
        ## dplyr::mutate(pert = stringr::str_remove(pert, "^__")) %>%
        dplyr::mutate(pert = stringr::str_remove(pert, stringr::fixed(".json"))) %>%
        dplyr::mutate(mean = (hi + lo) / 2,
               uncertainty = (hi - lo) / (range_to - range_from)) %>%
        tidyr::separate(pert, "__", into = c("muta", "leva", "mutb", "levb"),
                 fill = "right")
    return(processed_results)
}


#' Check for conflicts between perturbed nodes and background, ensures
#' that backgrounds take precedence.
#'
#' @param results Results from \code{\link{process_results}}
#' @param backgrounds Backgrounds
#' @param node_col node column name in backgrounds
#' @param drugs optional drugs data frame
#' @importFrom rlang .data
#' @export
check_conflicts <- function(results, backgrounds, node_col = "name", drugs = NULL) {

    check_conflict_row <- function(pert,
                                   lev,
                                   bkg,
                                   backgrounds,
                                   node_col = node_col) {
        x <- backgrounds %>%
            dplyr::filter(background == bkg,
                          .data[[node_col]] == {{pert}},
                          activity != lev)
        if (nrow(x) > 0) {
            conflict <- TRUE
        } else {
            conflict <- FALSE
        }
        return(conflict)
    }

    get_background_result <- function(case,
                                      background,
                                      muta,
                                      mutb,
                                      leva,
                                      levb,
                                      results_bkg,
                                      pheno) {

        if (is.na(pheno)) {
            x <- NA
        } else {

            if (case == "double") {
                x <- results_bkg %>%
                    dplyr::filter(case == {{case}},
                           background == {{background}},
                           muta == {{muta}},
                           mutb == {{mutb}},
                           leva == {{leva}},
                           levb == {{levb}},
                           node == {{pheno}})
                x <- dplyr::pull(x, mean)
            } else {
                x <- results_bkg %>%
                    dplyr::filter(case == {{case}},
                           background == {{background}},
                           muta == {{muta}},
                           leva == {{leva}},
                           node == {{pheno}})
                x <- dplyr::pull(x, mean)
            }
            return(x)
        }
    }

    conflicts <- results %>%
        dplyr::select(case, background, bkg_pert, muta, leva, mutb, levb) %>%
        dplyr::distinct() %>%
        dplyr::mutate(conflict_a = purrr::pmap_lgl(list(muta, leva, background),
                                                   check_conflict_row,
                                                   backgrounds = backgrounds,
                                                   node_col = node_col)
                      ) %>%
        dplyr::mutate(conflict_b = purrr::pmap_lgl(list(mutb, levb, background),
                                                   check_conflict_row,
                                                   backgrounds = backgrounds,
                                                   node_col = node_col)
                      ) %>%
        dplyr::mutate(conflict = conflict_a | conflict_b) %>%
        dplyr::filter(conflict == TRUE) %>%
        dplyr::mutate(mean_a = purrr::pmap_dbl(list(case = case,
                                                    background = background,
                                                    muta = muta,
                                                    mutb = mutb,
                                                    leva = leva,
                                                    levb = levb,
                                                    pheno = muta),
                                               get_background_result,
                                               results_bkg = results)) %>%
        dplyr::mutate(mean_b = purrr::pmap_dbl(list(case = case,
                                                    background = background,
                                                    muta = muta,
                                                    mutb = mutb,
                                                    leva = leva,
                                                    levb = levb,
                                                    pheno = mutb),
                                               get_background_result,
                                               results_bkg = results)) %>%
        dplyr::mutate(precedence =
                          dplyr::case_when(
                          ((conflict_a == TRUE & leva == mean_a) |
                           (conflict_b == TRUE & levb == mean_b)) ~
                              "perturbation",
                          TRUE ~ "background")
                      )

    if (unique(dplyr::pull(conflicts, precedence)) != "perturbation") {
        warning("Conflicts between background and perturbation detected that do not ALL conform to default of mutation taking precedence.")
    }

    return(conflicts)
}

##' Generate results directory for combinations in a standardised way,
##' so that visualisation scripts can generate one that lines up with
##' \code{\link{combo}} without combo having to pass it on

##' @title get_combo_results_dir
##' @param results_prefix prefix to results directory
##' @param project_path project path for git SHA log, point to git
##'     repo of the network and specification being tested
##' @param out_dir directory where all output files should be stored
##' @param netw_file_path path to network JSON file
##' @return string with path to results directory
##' @export
get_combo_results_dir <- function(results_prefix, project_path, out_dir, netw_file_path) {
    run_dir <- paste(results_prefix,
                                       stringr::str_remove(
                                                    basename(netw_file_path),
                                                    ".json"),
                                       sep = "_")
    if (project_path == "" || is.null(project_path)) {
        results_dir <- here::here(out_dir,
                                 run_dir)
    } else {
        results_dir <- here::here(project_path,
                                 out_dir,
                                 run_dir)
    }
    results_dir
}


##' Run all node and drug combinations (separately) for a given
##' network on a set of mutational backgrounds
##'
##' @title combo
##' @param netw_file_path path to network JSON file
##' @param backgrounds_path path to backgrounds (CSV)
##' @param drug_path path to list of drug perturbations to be applied
##'     in addition to node perturbations (CSV)
##' @param bma_path path to BMA command line installation, defaults to
##'     the path produced by the one click installer (.msi). The path
##'     is automatically normalized for cross-platform compatibility.
##' @param results_prefix prefix to results directory
##' @param out_dir output directory
##' @param project_path project path for git SHA log, point to git
##'     repo of the network and specification being tested
##' @param node_col_name name of the node column in the mutational
##'     background file and drug file
##' @param use_vmcai Use VMCAI mode
##' @param pheno_only Only evaluate the level of phenotype nodes
##'     supplied by the phenotypes argument. Speeds up processing step
##'     and reduces size of final processed_data file
##' @param phenotypes list of phenotypes in format `c("node_name_1",
##'     "node_name_2")` for use if pheno_only is TRUE
##' @param use_exclusions exclude perturbation of a set of nodes
##'     supplied to the `exclusions_path` argument. Speeds up
##'     processing by skipping those nodes which are uninteresting to
##'     perturb e.g. phenotype nodes
##' @param exclusions_path list of nodes in format `c("node_name_1",
##'     "node_name_2")` for use if use_exclusions is TRUE
##' @param drug_conflict_overide allow overide of drug conflicts
##'     check, only used for testing
##' @param skip_drugs_single  skip drug perturbations
##' @param skip_drugs_pairs skip drug perturbations
##' @param skip_all_pairs skip pairwise combinations of nodes
##' @param log_filename filename for log file
##' @return write a `parsed_results.csv` and `processed_results.csv`
##' @export
combo <- function(netw_file_path,
                  backgrounds_path,
                  drug_path,
                  bma_path =
                      'C:\\"Program Files (x86)"\\BMA\\BioCheckConsole.exe',
                  ## note exact format needed for BMA path
                  results_prefix = "COMBO_RUN",
                  out_dir,
                  project_path = "",
                  node_col_name = "node",
                  use_vmcai = TRUE,
                  pheno_only = FALSE,
                  phenotypes = NA,
                  use_exclusions = FALSE,
                  exclusions_path = NA,
                  drug_conflict_overide = FALSE,
                  skip_drugs_single = FALSE,
                  skip_drugs_pairs = FALSE,
                  skip_all_pairs = FALSE,
                  log_filename) {

    results_dir <- get_combo_results_dir(results_prefix = results_prefix,
                                         project_path = project_path,
                                         out_dir = out_dir,
                                         netw_file_path = netw_file_path)

    print(paste("Using results directory:", results_dir))

    # Handle empty project_path for directory creation
    base_out_dir <- if (project_path == "" || is.null(project_path)) {
        here::here(out_dir)
    } else {
        here::here(project_path, out_dir)
    }

    if (!dir.exists(base_out_dir)) {
        dir.create(base_out_dir)
    }

    if (!dir.exists(file.path(results_dir))) {
        dir.create(file.path(results_dir))
    }

    log_file <- file.path(results_dir, log_filename)
    futile.logger::flog.appender(
                       futile.logger::appender.file(log_file),
                       name = log_file)
    ## Capture all unflogged warnings and errors in flogger
    ## https://github.com/zatonovo/futile.logger/issues/36
    options(error = function()
        futile.logger::flog.warn(geterrmessage(), name = log_file))
    futile.logger::flog.info("Start", name = log_file)

    futile.logger::flog.info(paste("Running Combo on model:",
                                   netw_file_path,
                                   "with backgrounds",
                                   basename(backgrounds_path)),
                             name = log_file)
    futile.logger::flog.info(paste("Using VMCAI?:", use_vmcai), name = log_file)


    ## Main ----

    backgrounds <- readr::read_csv(backgrounds_path, show_col_types = FALSE, lazy = FALSE)
    if ((!skip_drugs_single) | (!skip_drugs_pairs)) {
        drugs <- import_drugs_clean(drug_path = drug_path)
    }
    netw_variables <- get_netw_variables(netw_file_path = netw_file_path) %>%
        dplyr::rename("node" = "name")
    ## dplyr::mutate(node = janitor::make_clean_names(node)) #TEMP

    ## TEMP get rid of weird character encoding of RangeTo in json
    netw_variables <- netw_variables %>%
        dplyr::mutate(range_to = as.integer(range_to))

    backgrounds <- backgrounds %>%
        dplyr::mutate(background =
                   purrr::map_chr(background, janitor::make_clean_names))
    if (!all(unique(dplyr::pull(backgrounds, dplyr::all_of(node_col_name))) %in%
             unique(dplyr::pull(netw_variables, dplyr::all_of(node_col_name))))) {
        stop("Nodes in background not in network")
    }

    background_commands <- make_bkg_commands_combo(
        backgrounds = backgrounds,
        netw_variables = netw_variables,
        node_col = "node")

    if (use_exclusions == TRUE) {
        exclusions <- readr::read_csv(exclusions_path, show_col_types = FALSE, lazy = FALSE) %>%
            dplyr::distinct() %>%
            purrr::as_vector()

        futile.logger::flog.warn(
                           paste("Nodes excluded from analysis:",
                                 exclusions),
                           name = log_file)
    } else {
        exclusions <- NA
    }

    s_muts <- make_single_muts(netw_variables = netw_variables %>%
                 dplyr::filter(!(.data[[node_col_name]] %in% exclusions)),
                               node_col = "node")

    pairs <- make_pair_muts(netw_variables = netw_variables %>%
                 dplyr::filter(!(.data[[node_col_name]] %in% exclusions)),
                            node_col = "node")


    ## Drugs ---------------------------

    if((!skip_drugs_single) | (!skip_drugs_pairs)) {
        ## Check if nodes affected by drugs are in the supplied network JSON
        check_drug_nodes(drugs = drugs,
                         netw_variables = netw_variables,
                         node_col_name = node_col_name)

        ## Check if any drug effects conflict
        if(drug_conflict_overide == FALSE) {
            check_drug_conflicts(drugs = drugs, node_col_name = node_col_name)
        } else {
            futile.logger::flog.warn(warning("Check for drug conflicts overidden"))
        }

        ## Make drug commands for each node
        drugs_commands <- get_drugs_commands(drugs = drugs,
                                             node_col_name = node_col_name,
                                             netw_variables = netw_variables)

        ## Check if drug commands are in range of network nodes
        check_drugs_in_range(drugs_commands = drugs_commands)

        ## Combine all perturbations for each drug for single and double
        ## perturbations
        drugs_single <- make_single_drugs(drugs_commands = drugs_commands)
        drugs_pairs <- make_pair_drugs(drugs_single = drugs_single)
    }

    ## Combine normal and drug perturbations
    if (!skip_drugs_single) {
        s_muts_w_drugs <- dplyr::bind_rows(s_muts, drugs_single)
    } else {
        warning("Skipping drug singles")
        s_muts_w_drugs <- s_muts %>%
            dplyr::mutate(alt_filename_part = NA)
    }

    if (!skip_drugs_pairs) {
        pairs_w_drugs <- dplyr::bind_rows(pairs, drugs_pairs)
    } else {
        warning("Skipping drug pairs")
        pairs_w_drugs <- pairs %>%
            dplyr::mutate(alt_filename_part = NA)
    }

    ##-----------------------------------

    ## make a baseline/no perturbation run for each background
    tictoc::tic("Run BMA")
    tictoc::tic("Run all single")
    run_all_backgrounds(background_commands = background_commands,
                        netw_file_path = netw_file_path,
                        bma_path = bma_path,
                        perts = s_muts_w_drugs,
                        combo_type = "single",
                        results_dir  = results_dir,
                        log_file = log_file)
    futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)

    if (!skip_all_pairs) {
        tictoc::tic("Run all double")
        run_all_backgrounds(background_commands = background_commands,
                            netw_file_path = netw_file_path,
                            bma_path = bma_path,
                            perts = pairs_w_drugs,
                            combo_type = "double",
                            results_dir  = results_dir,
                            log_file = log_file)
        futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)
        futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)
    } else {
        warning("Skipping pairs")
    }
    ## Parse results and save cache


    tictoc::tic("Parse")
    futile.logger::flog.info(print("Parsing results"), name = log_file)

    parsed_results_file <- file.path(results_dir, "parsed_results.csv")

    if (file.exists(parsed_results_file)) {
        parsed_results <- parse_biocheck_dir_apend(
            existing_file = parsed_results_file,
            dir = results_dir,
            netw_variables = netw_variables,
            rec = TRUE)
    } else {
        parsed_results <- parse_biocheck_dir(dir = results_dir,
                                             netw_variables = netw_variables,
                                             rec = TRUE)
    }

    readr::write_csv(parsed_results,
              file = parsed_results_file)
    futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)

    ## Process results and save cache

    tictoc::tic("Process results")
    results <- process_results(parsed_results = parsed_results,
                               phenotypes = phenotypes,
                               node_col = "node",
                               pheno_only = pheno_only,
                               log_file = log_file)
    readr::write_csv(results, file.path(results_dir, "processed_results.csv"))
    futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)

    if (pheno_only == FALSE) {
        if ((!skip_drugs_single) | (!skip_drugs_pairs)) {
            tictoc::tic("Conflicts")
            conflicts <- check_conflicts(results = results,
                                         backgrounds = backgrounds,
                                         node_col = node_col_name,
                                         drugs = drugs)
            readr::write_csv(conflicts, file.path(results_dir, "conflicts.csv"))
            futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)
        } else {
            tictoc::tic("Conflicts")
            conflicts <- check_conflicts(results = results,
                                         backgrounds = backgrounds,
                                         node_col = node_col_name)
            readr::write_csv(conflicts, file.path(results_dir, "conflicts.csv"))
            futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)
        }
    } else {
        futile.logger::flog.warn(warning("When running in pheno_only mode, cannot check conflicts between mutation and background"))
    }

    futile.logger::flog.info(capture.output(tictoc::toc()), name = log_file)



    futile.logger::flog.info(print("Combinations done"), name = log_file)
    futile.logger::flog.info("End", name = log_file)
}
