## Copyright 2022 Matthew A. Clarke, Fisher Lab <matthewaclarke1991@gmail.com>

##' Allow the conversion of a specification written with relative
##' terms (min, mid, max) for the perturbation and expectation to be
##' converted to absolute numbers for passing to BioCheckConsole
##' (BMA). This is safer as it will continue to produce the expected
##' result even when the granularity of a node changes.
##' @title convert_spec_levels
##' @param spec specification dataframe generated by
##'     \code{\link{import_spec}}
##' @param log_file name of log file
##' @return specification data frame with absolute numerical values
##'     for perturbation and expectation to be passed to
##'     BioCheckConsole
##' @export
convert_spec_levels <- function(spec, log_file) {
    if (is.character(dplyr::pull(spec, perturbation)) &
        is.character(dplyr::pull(spec, expected_result_bma))) {
        spec_levels <- spec %>%
            dplyr::mutate(perturbation_bma = dplyr::case_when(
                       stringr::str_detect(perturbation, stringr::regex("min", ignore_case = TRUE)) ~ as.numeric(range_from),
                       stringr::str_detect(perturbation, stringr::regex("max", ignore_case = TRUE)) ~ as.numeric(range_to),
                       stringr::str_detect(perturbation, stringr::regex("mid", ignore_case = TRUE)) ~
                           as.numeric((range_to + range_from) / 2),
                       stringr::str_detect(perturbation, "[[:digit:]]") ~
                           as.numeric(perturbation),
                       is.na(perturbation)             ~ as.numeric(NA)
                   )
                   ) %>%
            dplyr::mutate(expectation_bma = dplyr::case_when(
                       stringr::str_detect(expected_result_bma, stringr::regex("min", ignore_case = TRUE)) ~
                           as.numeric(range_from),
                       stringr::str_detect(expected_result_bma, stringr::regex("max", ignore_case = TRUE)) ~
                           as.numeric(range_to),
                       stringr::str_detect(expected_result_bma, stringr::regex("mid", ignore_case = TRUE)) ~
                           as.numeric((range_to + range_from) / 2),
                       stringr::str_detect(expected_result_bma, "[[:digit:]]") ~
                           as.numeric(expected_result_bma),
                       is.na(expected_result_bma)             ~ as.numeric(NA)
                   )
                   )
        futile.logger::flog.warn(
                           warning("Converted 'min', 'max','mid' levels to numeric in specification",
                                         call. = FALSE),
                                 name = log_file
                                 )
    } else {
        futile.logger::flog.warn(
                           warning("Using exact numeric values for perturbations
and expected results in the specification or background mutations
may give misleading results if the node granularities change.",
call. = FALSE),
name = log_file
)
        spec_levels <- spec %>%
            dplyr::mutate(perturbation_bma = perturbation) %>%
            dplyr::mutate(expectation_bma = expected_result_bma)
    }
    return(spec_levels)
}
