## Copyright 2022 Matthew A. Clarke, Fisher Lab <matthewaclarke1991@gmail.com>

##' import specification for autopert testing
##' @title import spec
##' @param spec_path path to specification csv file
##' @param loserum option to set all serum nodes to 1 (experimental)
##' @param clean_underscores remove all underscores at start of a
##'     string in source and cell line columns (as often conversion to
##'     csv adds them)
##' @param netw_variables network variables dataframe generated by
##'     \code{\link{get_netw_variables}}
##' @return specification data frame
##' @export
import_spec <- function(spec_path,
                        loserum,
                        clean_underscores,
                        netw_variables) {
    spec <- readr::read_csv(spec_path, lazy = FALSE, show_col_types = FALSE) %>%
        janitor::remove_empty(which = c("rows", "cols")) %>%
        dplyr::mutate(experiment_particular =
                   factor(experiment_particular,
                          levels = unique(experiment_particular)
                          )
               ) # preserve order
    ## TEMP Clean underscores from input files
    if (clean_underscores == TRUE) {
        spec <- spec %>%
            dplyr::mutate(source = gsub("^_", "", source)) %>%
            dplyr::mutate(cell_line = gsub("^_", "", cell_line))
    }
    ## TEMP See how results change if assume serum = 1
    if (loserum == TRUE) {
        spec <- spec %>%
            dplyr::mutate(perturbation =
                              dplyr::case_when(
                       gene == "SERUM" ~ 1,
                       TRUE ~ perturbation
                   )
                   )
        futile.logger::flog.warn(warning("Using SERUM level 1",
                                         call. = FALSE),
                                 name = log_file
                                 )
    }
    spec <- dplyr::left_join(spec, netw_variables, by = c("gene" = "name")) %>%
        dplyr::mutate(range_from = as.integer(range_from),
                      range_to = as.integer(range_to))
    
    # Validate that perturbation and expected_result_bma columns contain only integers
    if ("perturbation" %in% colnames(spec)) {
        perturbation_values <- spec$perturbation
        if (is.numeric(perturbation_values)) {
            check_integer_values(perturbation_values, "perturbation", "spec file")
        }
    }
    
    if ("expected_result_bma" %in% colnames(spec)) {
        expected_values <- spec$expected_result_bma
        if (is.numeric(expected_values)) {
            check_integer_values(expected_values, "expected_result_bma", "spec file")
        }
    }
    
    return(spec)
}
