## Copyright 2022 Matthew A. Clarke, Fisher Lab <matthewaclarke1991@gmail.com>

##' Stop if there are nodes which are perturbed in the specification
##' that are not in the network
##'
##' @title stop_missing_nodes_perturbed
##' @param spec specification dataframe generated by \code{\link{import_spec}}
##' @param missing_nodes_perturbed_overide allows overide of this check
##' @param netw_variables network variables dataframe generated by
##'     \code{\link{get_netw_variables}}
##' @param log_file name of log file
##' @return stop if nodes perturbed in specification are missing from network
##' @export
stop_missing_nodes_perturbed <- function(spec,
                                         missing_nodes_perturbed_overide = FALSE,
                                         netw_variables,
                                         log_file) {
    ## Check that all genes mutated in spec have a corresponding node
    ## in the network
    nodes_perturbed <- spec %>%
        dplyr::filter(!is.na(perturbation)) %>%
        dplyr::pull(gene) %>%
        unique()

    nodes_in_netw <- netw_variables %>%
        dplyr::pull(name) %>%
        unique()

    missing_nodes_perturbed <-
        dplyr::setdiff(nodes_perturbed, nodes_in_netw)

    message <- paste0(length(missing_nodes_perturbed),
                      " Nodes which are perturbed in the specification are missing from the provided BMA network: \n",
                      paste0(missing_nodes_perturbed, collapse =  "\n"))

    if (length(missing_nodes_perturbed) > 0) {
        if (missing_nodes_perturbed_overide == TRUE) {
            flog.warn(
                warning(paste0(message), call. = FALSE),
                name = log_file
            )
        } else {
            futile.logger::flog.error(
                stop(paste0(message), call. = FALSE),
                name = log_file
            )
        }
    }
}
