## Copyright 2022 Matthew A. Clarke, Fisher Lab, UCL <matthew.clarke@ucl.ac.uk>

#' Stop if there is an experiment that does not perturb the network
#' at all as usually this indicates a user error in the formating of
#' the specification
#'
#' @title stop_no_inputs
#' @param spec specification dataframe generated by \code{\link{import_spec}}
#' @param log_file log_file name
#' @param group_vars variables used to group experiments
#' @return stop if there is an experiment with no inputs
#' @export
stop_no_inputs <- function(spec, log_file, group_vars) {
    no_inputs <- spec %>%
        dplyr::mutate(approx_csv_row_id = 1 + seq_len(nrow(.))) %>%
        dplyr::group_by(across(all_of(group_vars))) %>%
        dplyr::reframe(n_blank_input = sum(is.na(perturbation)),
                       n_total = dplyr::n(), csv_row_id = approx_csv_row_id) %>%
        dplyr::filter(n_blank_input == n_total)
    if (nrow(no_inputs) > 0) {
        futile.logger::flog.error(
            stop(
                "There are cases where there are no perturbations of the network, only
      measurement of the basal output. Currently (2020-02-26) this will cause
      an error. Normally would expect `n_total` an experiment to be
      greater than `n_blank_input` which are usually nodes where one is
      measuring the output.
      In spec there are: \n",
      paste(utils::capture.output(no_inputs), collapse = "\n"),
      call. = FALSE
      ),
      name = log_file
      )
    }
}
