## Copyright 2022 Matthew A. Clarke, Fisher Lab <matthewaclarke1991@gmail.com>

##' Stop if there are nodes which are measured/expected in the specification
##' that are not in the network
##'
##' @title stop_missing_nodes_expected
##' @param spec specification dataframe generated by \code{\link{import_spec}}
##' @param missing_nodes_expected_overide allows overide of this check
##' @param netw_variables network variables dataframe generated by
##'     \code{\link{get_netw_variables}}
##' @param log_file name of log file
##' @return  stop if nodes expected/measured in specification are missing from network
##' @export
stop_missing_nodes_expected <- function(spec,
                                        missing_nodes_expected_overide = FALSE,
                                        netw_variables,
                                        log_file) {
    ## Check if there are nodes missing that are to be measured only
    nodes_expected <- spec %>%
        dplyr::filter(!is.na(expected_result_bma)) %>%
        dplyr::pull(gene) %>%
        unique()

    nodes_in_netw <- netw_variables %>%
        dplyr::pull(name) %>%
        unique()

    missing_nodes_expected <-
        dplyr::setdiff(nodes_expected, nodes_in_netw)

    message <- paste0(length(missing_nodes_expected),
                      " nodes, which were measured in the experiments, for which there is an expected result, in the specification are missing from the provided BMA network: \n",
                      paste0(missing_nodes_expected, collapse = ",\n"))

    if (length(missing_nodes_expected) > 0) {
        if (missing_nodes_expected_overide == TRUE) {
            futile.logger::flog.warn(
                warning(paste0(message), call. = FALSE),
                name = log_file
            )
        } else {
            futile.logger::flog.error(
                stop(paste0(message), call. = FALSE),
                name = log_file
            )
        }
    }
}
